# Generated by Django 3.1.4 on 2021-02-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0003_auto_20210223_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user/default.png', null=True, upload_to='user/'),
        ),
    ]
