# Generated by Django 3.1.4 on 2021-02-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0006_auto_20210226_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salaryH',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salaryL',
            field=models.PositiveIntegerField(),
        ),
    ]
