# Generated by Django 3.1.4 on 2021-03-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0008_jobpost_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='qualification',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
