# Generated by Django 3.1.4 on 2021-03-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0009_jobpost_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
